name: Deploy on Commit

on:
  push:
    branches:
      - main  # Adjust to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Execute Bash script on EC2
      id: ssh
      run: |
        set -e
        # Define the directory to list, change if needed
        DIRECTORY_TO_LIST="/home/ubuntu"

        # List the contents of the directory on the EC2 instance
        if ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_DNS }} "ls -a $DIRECTORY_TO_LIST"; then
          echo "Directory listing succeeded, proceeding with the update script."
          
          # Execute the update script
          if ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_DNS }} sudo bash < /home/ubuntu/update.sh; then
            echo "SSH command succeeded, sending notification to Slack"
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Github update script initiated."}' ${{ secrets.SLACK_WEBHOOK_URL }}
          else
            echo "SSH command failed, sending notification to Slack"
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Github update script initiation failed!"}' ${{ secrets.SLACK_WEBHOOK_URL }}
            exit 1
          fi
        else
          echo "Directory listing failed, sending notification to Slack"
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Failed to list directory contents on EC2 instance!"}' ${{ secrets.SLACK_WEBHOOK_URL }}
          exit 1
        fi

